version: "3.3"

networks:
  users-service-network:

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - users-service-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - users-service-network

volumes:
  mongodb_data:
