# @host = http://localhost:8010
@host = http://103.82.92.117:8010


### test
GET {{host}}/


### get all users
GET {{host}}/api/v1/user/all


### get one user
GET {{host}}/api/v1/user/66c072889121a44cc12bb58d


### get one user by email
GET {{host}}/api/v1/user/email/mymail


### create a user
POST {{host}}/api/v1/user 
Content-Type: application/json

{
    "username":"didi",
    "email":"mymail",
    "password":"rahasia123"
}


### update a user
PATCH {{host}}/api/v1/user/66bd914f7340ba582f5c8c43 
Content-Type: application/json

{
    "username":"Wahyu"
}


### delete a user
DELETE {{host}}/api/v1/user/66bd914f7340ba582f5c8c43